In [ ]:
import numpy as np

sentence = ["What", "are", "the", "symptoms", "of", "diabetes", "?"]
np.random.seed(42)

d_model = 8
d_k = 4

embeddings = np.random.randn(len(sentence), d_model)

W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_k)

Q = embeddings @ W_Q
K = embeddings @ W_K
V = embeddings @ W_V

scores = Q @ K.T / np.sqrt(d_k)

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)

attention_weights = softmax(scores)
output = attention_weights @ V

print("Tokens:", sentence)
print("\nAttention Scores (raw):\n", np.round(scores, 3))
print("\nAttention Weights (after softmax):\n", np.round(attention_weights, 3))
print("\nSelf-Attention Output:\n", np.round(output, 3))

Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']

Attention Scores (raw):
 [[  0.7     6.234   1.948   4.741  15.904   2.37    4.496]
 [  0.205 -11.452  -4.807  -3.791 -10.526   0.97    7.204]
 [  2.575 -14.505  -0.396 -12.305 -23.299  -5.703  -0.634]
 [ -3.025  11.352  -3.403  10.706   8.128   4.532  -6.949]
 [  3.296 -12.077  -0.604  -6.261  -1.59   -0.203  14.069]
 [ -1.946  12.686  -1.438  10.654  13.445   4.288  -4.864]
 [  0.17   12.027   4.793   5.482  17.141   0.644  -2.543]]

Attention Weights (after softmax):
 [[0.    0.    0.    0.    1.    0.    0.   ]
 [0.001 0.    0.    0.    0.    0.002 0.997]
 [0.916 0.    0.047 0.    0.    0.    0.037]
 [0.    0.639 0.    0.335 0.025 0.001 0.   ]
 [0.    0.    0.    0.    0.    0.    1.   ]
 [0.    0.306 0.    0.04  0.654 0.    0.   ]
 [0.    0.006 0.    0.    0.994 0.    0.   ]]

Self-Attention Output:
 [[-0.104 -6.905  5.888 -0.015]
 [ 1.103 -2.414 -0.493 -0.148]
 [-0.287  0.722 -2.801  0.028]
 [-0.509 -1.288  4.072 